Fixing command line `swift test` failure on both macOS / Linux
The test folder name mismatched with project name and caused trouble
like this:
```
Linking
./.build/x86_64-apple-macosx10.10/debug/PerfectSessionPackageTests.xctes
t/Contents/MacOS/PerfectSessionPackageTests
Undefined symbols for architecture x86_64:
  "__T014PerfectSession12CSRFSecurityC7isValidSbSS6origin_SS4hosttFZ",
referenced from:
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu_ in
Perfect_SessionTests.swift.o
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu0_ in
Perfect_SessionTests.swift.o
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu1_ in
Perfect_SessionTests.swift.o
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu2_ in
Perfect_SessionTests.swift.o
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu3_ in
Perfect_SessionTests.swift.o
  "__T014PerfectSession12CSRFSecurityCMa", referenced from:
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu_ in
Perfect_SessionTests.swift.o
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu0_ in
Perfect_SessionTests.swift.o
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu1_ in
Perfect_SessionTests.swift.o
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu2_ in
Perfect_SessionTests.swift.o
      __T020Perfect_SessionTestsAAC10testValidsyyFSbyKXKfu3_ in
Perfect_SessionTests.swift.o
ld: symbol(s) not found for architecture x86_64

```